'use client'

import Image from 'next/image'
import { useEffect, useState } from 'react'
import { DotPattern } from '@/components/ui/dot-pattern'
import { cn } from '@/lib/utils'
import { CloudinaryPicture } from './cloudinary-picture'
import breakpointsData from '@/data/cloudinary-breakpoints.json'

// Generated by `pnpm cloudinary:breakpoints`; keyed by Cloudinary public ID.
const breakpoints: Record<string, number[]> = breakpointsData

interface PostImageProps {
  src?: string
  alt: string
  placeholder?: string
  sizes?: string
  loading?: 'lazy' | 'eager'
  unoptimized?: boolean
  hoverScale?: boolean
  className?: string
}

export function PostImage({
  src,
  alt,
  placeholder,
  sizes = '(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw',
  loading = 'lazy',
  unoptimized = false,
  hoverScale = false,
  className,
}: PostImageProps) {
  const [loaded, setLoaded] = useState(false)
  const [error, setError] = useState(false)

  useEffect(() => {
    setLoaded(false)
    setError(false)
  }, [src])

  if (!src || src === '') {
    return (
      <div className={cn('relative w-full h-full flex items-center justify-center bg-muted', className)}>
        {placeholder && <span className="text-sm text-muted-foreground">{placeholder}</span>}
      </div>
    )
  }

  // Logic to determine if we should use the Cloudinary Responsive pipeline
  // 1. Strip leading slash and extension for lookup
  const publicId = src.replace(/^\/+/, '').replace(/\.[^.]+$/, '')
  const hasBreakpoints = breakpoints[publicId]

  // Cloudinary IS the optimization (jxl/avif/webp via CDN), so route any image
  // with generated breakpoints through it even when `unoptimized` is set — that
  // flag only means "skip next/image", which doesn't apply to the <picture> path.
  if (hasBreakpoints) {
    return (
      <CloudinaryPicture
        src={publicId}
        alt={alt}
        sizes={sizes}
        breakpoints={breakpoints[publicId]}
        className={cn('transition-transform duration-300', hoverScale && 'group-hover:scale-105', className)}
      />
    )
  }

  const hasImage = !error

  return (
    <>
      {!loaded && (
        <>
          <DotPattern
            width={20}
            height={20}
            cx={1}
            cy={1}
            cr={1}
            className={cn(
              'fill-muted-foreground/20 transition-transform duration-300',
              hoverScale && 'group-hover:scale-105',
            )}
          />
          {placeholder !== undefined && placeholder !== '' && (
            <span className="text-muted-foreground absolute inset-0 flex items-center justify-center text-sm">
              {placeholder}
            </span>
          )}
        </>
      )}
      {hasImage && (
        <Image
          src={src}
          alt={alt}
          fill
          sizes={sizes}
          loading={loading}
          unoptimized={unoptimized}
          className={cn(
            'object-cover transition-transform duration-300',
            hoverScale && 'group-hover:scale-105',
            className,
          )}
          onLoad={() => setLoaded(true)}
          onError={() => setError(true)}
        />
      )}
    </>
  )
}
